### ISSUE TITLE
image in README.md is of old mark3 design.

### ISSUE THREAD

**Issue by claybabe** [BainbridgeArtisanResourceNetwork/Mark4_printer#19]

**Comment by mikeabuilder** [comment]
Hi Clayton,

 

Hope this message reaches you, and hope you are staying safe. We've missed you in the large 3D printer meetings since we got back into the studio in October. That lasted less than 2 months. We're back on virtual meetings as of this week, and expect to continue this way at least until mid-December, but I think probably much longer.

 

Progress on the printer has been slow, but Ralph has been making great progress on the electronics. He's got all the motors hooked up and is able to move the carriage around. Also move the bed up and down.  We've got a new prototype where the belts connect to the carriage. Still needs work, but it has an arrangement that equalizes the tensions in both belts and the tightening is done with the tuning machine from a ukulele. Kind of goofy looking, but it seems to work.

 

Anyway, hope things are good in your world and hope to see you back at BARN some day.

 

Mike
